spring:
  datasource:
    url: jdbc:mysql://aws-takehome-exam-db.cntto8inh5kh.us-east-1.rds.amazonaws.com:3306/SCHOOL
    username: admin
    password: password1
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
  jpa:
    show-sql: true